### ISSUE TITLE
 SecKeychainSearchCopyNext: The specified item could not be found in the keychain.\n'

### ISSUE THREAD

**Issue by oo1993448102** [cls1991/ng#6]
The specified item could not be found in the keychain.\n'

**Comment by cls1991** [comment]
It's most likely that the wifi ssid you hacked is illegal,  you can simply print the ssid.

**Comment by oo1993448102** [comment]
it only consists of capital English letters and '-'

**Comment by cls1991** [comment]
Something may be wrong,  you can compare the result with your real wifi ssid.
https://github.com/cls1991/ng/blob/7f23957b2171c7dc38cd06b3c75de3465f0786f6/ng.py#L54

**Comment by oo1993448102** [comment]
the result of  match.group('ssid') is 'MG-WII\n            MCS: 15\n        channel: 149\n'b''' , maybe it should only be 'MG-WII',sorry that im not that familiar with python

**Comment by cls1991** [comment]
It's fixed. Thanks for your tests. 😸
